# the function can make a special list that store some information about a martix.
makeCacheMatrix <- function(x = matrix()) {
        m <- NULL
        set <- function(y) {
                x <<- y
                m <<- NULL
        }
        # The code "m <<- NULL" can avoid the value of the "m" generated by the function last time interfere the outcome of this function.
        get <- function() x
        set_t <- function(t) m <<- t
        # t is the function that can generate an inversed matrix.
        get_t <- function() m
        list(set = set, get = get,
             set_t = set_t,
             get_t = get_t)
        
}


# The argument of this function should be a variable which contain the output of the first function.

cacheSolve <- function(x, ...) {
        ## Return a matrix that is the inverse of 'x'
        m <- x$get_t()
        if(!is.null(m)) {
                message("getting cached data")
                return(m)
        }
        data <- x$get()
        m <- t(data, ...)
        x$set_t(m)
        m
}
